# Generated by Django 4.1 on 2022-08-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('empid', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phnnum', models.CharField(max_length=10)),
                ('rank', models.IntegerField()),
                ('officeRoom', models.IntegerField()),
                ('wing', models.CharField(max_length=1)),
                ('hostel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phnNum', models.CharField(max_length=10)),
                ('room', models.IntegerField()),
                ('wing', models.CharField(max_length=1)),
                ('hostel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
